version: '3.7'

services:
  movies-api:
    restart: on-failure
    container_name: movies-api
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - static_volume:/home/app/web/project/static
      - ./:/usr/src/app:cached
    ports:
      - 8080:3000
  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - 6379:6379
    container_name: redis-broker
volumes:
  static_volume: