version: '3.7'

services:
  movies-api:
    restart: on-failure
    container_name: movies-api
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - static_volume:/home/app/web/project/static
      - ./:/usr/src/app:cached
    depends_on:
      - mongo
    ports:
      - 8080:3000
  mongo:
    image: mvertes/alpine-mongo
    ports:
      - 27099:27017
    volumes:
      - mongo_data:/var/lib/mongo/data/
    container_name: mongo

volumes:
  static_volume:
  mongo_data: